### ISSUE TITLE
Error: A value of type 'ValueNotifier<_Enum>' can't be assigned to a variable of type 'ValueNotifier<V>'.

### ISSUE THREAD

**Issue by mousam17** [cahyofendhi/Flutter-Cinema#11]
flutter_windows_2.8.1-stable/flutter/.pub-cache/hosted/pub.dartlang.org/pull_to_refresh-1.6.5/lib/src
/internals/indicator_wrap.dart:632:9: Error: A value of type 'ValueNotifier<_Enum>' can't be assigned to a variable of
type 'ValueNotifier<V>'.
 - 'ValueNotifier' is from 'package:flutter/src/foundation/change_notifier.dart'
 ('../../../Softwares/flutter_windows_2.8.1-stable/flutter/packages/flutter/lib/src/foundation/change_notifier.dart').
 - '_Enum' is from 'dart:core'.
        ? refresher.controller.headerMode
        ^

**Comment by cahyofendhi** [comment]
please pull again, I've fixed it @mousam17

**Comment by zulfios** [comment]
@cahyofendhi 
can u tell me how to fix it bro? i have problem with this error hehe
